language: julia
os:
  - osx
  - linux
julia:
  - 0.4
  - 0.3
sudo: required
notifications:
  email: false
before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("OpenStreetMap", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("OpenStreetMap")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
